# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikolas/Documents/ufrgs/cg/assign2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikolas/Documents/ufrgs/cg/assign2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikolas/Documents/ufrgs/cg/assign2/CMakeFiles /home/nikolas/Documents/ufrgs/cg/assign2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikolas/Documents/ufrgs/cg/assign2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CMP143

# Build rule for target.
CMP143: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CMP143
.PHONY : CMP143

# fast build rule for target.
CMP143/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/build
.PHONY : CMP143/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/CMakeFiles/uninstall.dir/build.make lib/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/src/CMakeFiles/glfw.dir/build.make lib/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

lib/FileBrowser/ImGuiFileBrowser.o: lib/FileBrowser/ImGuiFileBrowser.cpp.o
.PHONY : lib/FileBrowser/ImGuiFileBrowser.o

# target to build an object file
lib/FileBrowser/ImGuiFileBrowser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/FileBrowser/ImGuiFileBrowser.cpp.o
.PHONY : lib/FileBrowser/ImGuiFileBrowser.cpp.o

lib/FileBrowser/ImGuiFileBrowser.i: lib/FileBrowser/ImGuiFileBrowser.cpp.i
.PHONY : lib/FileBrowser/ImGuiFileBrowser.i

# target to preprocess a source file
lib/FileBrowser/ImGuiFileBrowser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/FileBrowser/ImGuiFileBrowser.cpp.i
.PHONY : lib/FileBrowser/ImGuiFileBrowser.cpp.i

lib/FileBrowser/ImGuiFileBrowser.s: lib/FileBrowser/ImGuiFileBrowser.cpp.s
.PHONY : lib/FileBrowser/ImGuiFileBrowser.s

# target to generate assembly for a file
lib/FileBrowser/ImGuiFileBrowser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/FileBrowser/ImGuiFileBrowser.cpp.s
.PHONY : lib/FileBrowser/ImGuiFileBrowser.cpp.s

lib/gl3w.o: lib/gl3w.c.o
.PHONY : lib/gl3w.o

# target to build an object file
lib/gl3w.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/gl3w.c.o
.PHONY : lib/gl3w.c.o

lib/gl3w.i: lib/gl3w.c.i
.PHONY : lib/gl3w.i

# target to preprocess a source file
lib/gl3w.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/gl3w.c.i
.PHONY : lib/gl3w.c.i

lib/gl3w.s: lib/gl3w.c.s
.PHONY : lib/gl3w.s

# target to generate assembly for a file
lib/gl3w.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/gl3w.c.s
.PHONY : lib/gl3w.c.s

lib/imgui/imgui.o: lib/imgui/imgui.cpp.o
.PHONY : lib/imgui/imgui.o

# target to build an object file
lib/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui.cpp.o
.PHONY : lib/imgui/imgui.cpp.o

lib/imgui/imgui.i: lib/imgui/imgui.cpp.i
.PHONY : lib/imgui/imgui.i

# target to preprocess a source file
lib/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui.cpp.i
.PHONY : lib/imgui/imgui.cpp.i

lib/imgui/imgui.s: lib/imgui/imgui.cpp.s
.PHONY : lib/imgui/imgui.s

# target to generate assembly for a file
lib/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui.cpp.s
.PHONY : lib/imgui/imgui.cpp.s

lib/imgui/imgui_demo.o: lib/imgui/imgui_demo.cpp.o
.PHONY : lib/imgui/imgui_demo.o

# target to build an object file
lib/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_demo.cpp.o
.PHONY : lib/imgui/imgui_demo.cpp.o

lib/imgui/imgui_demo.i: lib/imgui/imgui_demo.cpp.i
.PHONY : lib/imgui/imgui_demo.i

# target to preprocess a source file
lib/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_demo.cpp.i
.PHONY : lib/imgui/imgui_demo.cpp.i

lib/imgui/imgui_demo.s: lib/imgui/imgui_demo.cpp.s
.PHONY : lib/imgui/imgui_demo.s

# target to generate assembly for a file
lib/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_demo.cpp.s
.PHONY : lib/imgui/imgui_demo.cpp.s

lib/imgui/imgui_draw.o: lib/imgui/imgui_draw.cpp.o
.PHONY : lib/imgui/imgui_draw.o

# target to build an object file
lib/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_draw.cpp.o
.PHONY : lib/imgui/imgui_draw.cpp.o

lib/imgui/imgui_draw.i: lib/imgui/imgui_draw.cpp.i
.PHONY : lib/imgui/imgui_draw.i

# target to preprocess a source file
lib/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_draw.cpp.i
.PHONY : lib/imgui/imgui_draw.cpp.i

lib/imgui/imgui_draw.s: lib/imgui/imgui_draw.cpp.s
.PHONY : lib/imgui/imgui_draw.s

# target to generate assembly for a file
lib/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_draw.cpp.s
.PHONY : lib/imgui/imgui_draw.cpp.s

lib/imgui/imgui_impl_glfw.o: lib/imgui/imgui_impl_glfw.cpp.o
.PHONY : lib/imgui/imgui_impl_glfw.o

# target to build an object file
lib/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_impl_glfw.cpp.o
.PHONY : lib/imgui/imgui_impl_glfw.cpp.o

lib/imgui/imgui_impl_glfw.i: lib/imgui/imgui_impl_glfw.cpp.i
.PHONY : lib/imgui/imgui_impl_glfw.i

# target to preprocess a source file
lib/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_impl_glfw.cpp.i
.PHONY : lib/imgui/imgui_impl_glfw.cpp.i

lib/imgui/imgui_impl_glfw.s: lib/imgui/imgui_impl_glfw.cpp.s
.PHONY : lib/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
lib/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_impl_glfw.cpp.s
.PHONY : lib/imgui/imgui_impl_glfw.cpp.s

lib/imgui/imgui_impl_opengl3.o: lib/imgui/imgui_impl_opengl3.cpp.o
.PHONY : lib/imgui/imgui_impl_opengl3.o

# target to build an object file
lib/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_impl_opengl3.cpp.o
.PHONY : lib/imgui/imgui_impl_opengl3.cpp.o

lib/imgui/imgui_impl_opengl3.i: lib/imgui/imgui_impl_opengl3.cpp.i
.PHONY : lib/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
lib/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_impl_opengl3.cpp.i
.PHONY : lib/imgui/imgui_impl_opengl3.cpp.i

lib/imgui/imgui_impl_opengl3.s: lib/imgui/imgui_impl_opengl3.cpp.s
.PHONY : lib/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
lib/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_impl_opengl3.cpp.s
.PHONY : lib/imgui/imgui_impl_opengl3.cpp.s

lib/imgui/imgui_tables.o: lib/imgui/imgui_tables.cpp.o
.PHONY : lib/imgui/imgui_tables.o

# target to build an object file
lib/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_tables.cpp.o
.PHONY : lib/imgui/imgui_tables.cpp.o

lib/imgui/imgui_tables.i: lib/imgui/imgui_tables.cpp.i
.PHONY : lib/imgui/imgui_tables.i

# target to preprocess a source file
lib/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_tables.cpp.i
.PHONY : lib/imgui/imgui_tables.cpp.i

lib/imgui/imgui_tables.s: lib/imgui/imgui_tables.cpp.s
.PHONY : lib/imgui/imgui_tables.s

# target to generate assembly for a file
lib/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_tables.cpp.s
.PHONY : lib/imgui/imgui_tables.cpp.s

lib/imgui/imgui_widgets.o: lib/imgui/imgui_widgets.cpp.o
.PHONY : lib/imgui/imgui_widgets.o

# target to build an object file
lib/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_widgets.cpp.o
.PHONY : lib/imgui/imgui_widgets.cpp.o

lib/imgui/imgui_widgets.i: lib/imgui/imgui_widgets.cpp.i
.PHONY : lib/imgui/imgui_widgets.i

# target to preprocess a source file
lib/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_widgets.cpp.i
.PHONY : lib/imgui/imgui_widgets.cpp.i

lib/imgui/imgui_widgets.s: lib/imgui/imgui_widgets.cpp.s
.PHONY : lib/imgui/imgui_widgets.s

# target to generate assembly for a file
lib/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/lib/imgui/imgui_widgets.cpp.s
.PHONY : lib/imgui/imgui_widgets.cpp.s

src/VAO.o: src/VAO.cpp.o
.PHONY : src/VAO.o

# target to build an object file
src/VAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/VAO.cpp.o
.PHONY : src/VAO.cpp.o

src/VAO.i: src/VAO.cpp.i
.PHONY : src/VAO.i

# target to preprocess a source file
src/VAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/VAO.cpp.i
.PHONY : src/VAO.cpp.i

src/VAO.s: src/VAO.cpp.s
.PHONY : src/VAO.s

# target to generate assembly for a file
src/VAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/VAO.cpp.s
.PHONY : src/VAO.cpp.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/matrices.o: src/matrices.cpp.o
.PHONY : src/matrices.o

# target to build an object file
src/matrices.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/matrices.cpp.o
.PHONY : src/matrices.cpp.o

src/matrices.i: src/matrices.cpp.i
.PHONY : src/matrices.i

# target to preprocess a source file
src/matrices.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/matrices.cpp.i
.PHONY : src/matrices.cpp.i

src/matrices.s: src/matrices.cpp.s
.PHONY : src/matrices.s

# target to generate assembly for a file
src/matrices.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/matrices.cpp.s
.PHONY : src/matrices.cpp.s

src/model_object.o: src/model_object.cpp.o
.PHONY : src/model_object.o

# target to build an object file
src/model_object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/model_object.cpp.o
.PHONY : src/model_object.cpp.o

src/model_object.i: src/model_object.cpp.i
.PHONY : src/model_object.i

# target to preprocess a source file
src/model_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/model_object.cpp.i
.PHONY : src/model_object.cpp.i

src/model_object.s: src/model_object.cpp.s
.PHONY : src/model_object.s

# target to generate assembly for a file
src/model_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/model_object.cpp.s
.PHONY : src/model_object.cpp.s

src/options_manager.o: src/options_manager.cpp.o
.PHONY : src/options_manager.o

# target to build an object file
src/options_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/options_manager.cpp.o
.PHONY : src/options_manager.cpp.o

src/options_manager.i: src/options_manager.cpp.i
.PHONY : src/options_manager.i

# target to preprocess a source file
src/options_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/options_manager.cpp.i
.PHONY : src/options_manager.cpp.i

src/options_manager.s: src/options_manager.cpp.s
.PHONY : src/options_manager.s

# target to generate assembly for a file
src/options_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/options_manager.cpp.s
.PHONY : src/options_manager.cpp.s

src/renderer.o: src/renderer.cpp.o
.PHONY : src/renderer.o

# target to build an object file
src/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/renderer.cpp.o
.PHONY : src/renderer.cpp.o

src/renderer.i: src/renderer.cpp.i
.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s
.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/tiny_obj_loader.o: src/tiny_obj_loader.cpp.o
.PHONY : src/tiny_obj_loader.o

# target to build an object file
src/tiny_obj_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/tiny_obj_loader.cpp.o
.PHONY : src/tiny_obj_loader.cpp.o

src/tiny_obj_loader.i: src/tiny_obj_loader.cpp.i
.PHONY : src/tiny_obj_loader.i

# target to preprocess a source file
src/tiny_obj_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/tiny_obj_loader.cpp.i
.PHONY : src/tiny_obj_loader.cpp.i

src/tiny_obj_loader.s: src/tiny_obj_loader.cpp.s
.PHONY : src/tiny_obj_loader.s

# target to generate assembly for a file
src/tiny_obj_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMP143.dir/build.make CMakeFiles/CMP143.dir/src/tiny_obj_loader.cpp.s
.PHONY : src/tiny_obj_loader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... CMP143"
	@echo "... glfw"
	@echo "... lib/FileBrowser/ImGuiFileBrowser.o"
	@echo "... lib/FileBrowser/ImGuiFileBrowser.i"
	@echo "... lib/FileBrowser/ImGuiFileBrowser.s"
	@echo "... lib/gl3w.o"
	@echo "... lib/gl3w.i"
	@echo "... lib/gl3w.s"
	@echo "... lib/imgui/imgui.o"
	@echo "... lib/imgui/imgui.i"
	@echo "... lib/imgui/imgui.s"
	@echo "... lib/imgui/imgui_demo.o"
	@echo "... lib/imgui/imgui_demo.i"
	@echo "... lib/imgui/imgui_demo.s"
	@echo "... lib/imgui/imgui_draw.o"
	@echo "... lib/imgui/imgui_draw.i"
	@echo "... lib/imgui/imgui_draw.s"
	@echo "... lib/imgui/imgui_impl_glfw.o"
	@echo "... lib/imgui/imgui_impl_glfw.i"
	@echo "... lib/imgui/imgui_impl_glfw.s"
	@echo "... lib/imgui/imgui_impl_opengl3.o"
	@echo "... lib/imgui/imgui_impl_opengl3.i"
	@echo "... lib/imgui/imgui_impl_opengl3.s"
	@echo "... lib/imgui/imgui_tables.o"
	@echo "... lib/imgui/imgui_tables.i"
	@echo "... lib/imgui/imgui_tables.s"
	@echo "... lib/imgui/imgui_widgets.o"
	@echo "... lib/imgui/imgui_widgets.i"
	@echo "... lib/imgui/imgui_widgets.s"
	@echo "... src/VAO.o"
	@echo "... src/VAO.i"
	@echo "... src/VAO.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrices.o"
	@echo "... src/matrices.i"
	@echo "... src/matrices.s"
	@echo "... src/model_object.o"
	@echo "... src/model_object.i"
	@echo "... src/model_object.s"
	@echo "... src/options_manager.o"
	@echo "... src/options_manager.i"
	@echo "... src/options_manager.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/tiny_obj_loader.o"
	@echo "... src/tiny_obj_loader.i"
	@echo "... src/tiny_obj_loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

